kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.19.1
  commands:
  - go env -w GOPROXY=https://goproxy.cn,direct
  - GOOS=linux GOARCH=amd64 go build -o drone-webhook
  - ls


- name: publish
  depends_on: [ build ]
  image: plugins/docker
  pull: if-not-exists
  settings:
    registry: registry.cn-shanghai.aliyuncs.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.cn-shanghai.aliyuncs.com/zzf2001/drone-webhook
    tags: latest
# - name: publish
#   image: plugins/docker
#   settings:
#     auto_tag: true
#     repo: ootd/dsa
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
