kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.19.0-alpine3.16
  commands:
  - go env -w GOPROXY=https://goproxy.cn,direct
  - go build
  - go test ./...

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: ootd/dsa
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
